In [1]:
!python CIS_zero_shot.py --model_name ViT-B/32

loading annotations into memory...
Done (t=0.63s)
creating index...
index created!
100%|███████████████████████████████████████| 1200/1200 [01:00<00:00, 19.75it/s]

**** Zero-shot CLIP's val accuracy: 54.37. ****

[0.91965855 0.70454545 0.70082645 0.46432818 0.76275304 0.59893048
 0.7926078  0.20055382 0.49275362 0.46026012]
[0.58777279 0.36556604 0.53875476 0.84432432 0.83882458 0.84955752
 0.49243999 0.51843236 0.43243243 0.89215686]
[0.71718062 0.48136646 0.6091954  0.59915612 0.79898219 0.70256142
 0.60746656 0.28922278 0.46062659 0.607245  ]


In [2]:
!python CIS_zero_shot.py --model_name ViT-B/16

loading annotations into memory...
Done (t=0.45s)
creating index...
index created!
100%|███████████████████████████████████████| 1200/1200 [00:56<00:00, 21.15it/s]

**** Zero-shot CLIP's val accuracy: 63.01. ****

[0.86378653 0.58518519 0.42571255 0.66764418 0.71805556 0.75147232
 0.76757352 0.26806582 0.24901575 0.57621441]
[0.54541078 0.55896226 0.89199492 0.73837838 0.920748   0.80657396
 0.69188244 0.40229062 0.40222576 0.48179272]
[0.66863382 0.57177322 0.57635468 0.70123203 0.80686695 0.77804878
 0.72776521 0.32174037 0.30759878 0.52479024]


In [3]:
!python CIS_zero_shot.py --model_name ViT-L/14

loading annotations into memory...
Done (t=0.49s)
creating index...
index created!
100%|███████████████████████████████████████| 1200/1200 [02:38<00:00,  7.56it/s]

**** Zero-shot CLIP's val accuracy: 64.98. ****

[0.95718728 0.46082337 0.60152931 0.6213355  0.55019199 0.87692308
 0.79513281 0.19289216 0.58128079 0.71577726]
[0.64216945 0.81839623 0.89961881 0.82486486 0.89314337 0.57648546
 0.70860896 0.28167502 0.75039746 0.86414566]
[0.76865457 0.58963466 0.7209776  0.70877845 0.68092329 0.69565217
 0.74938164 0.22897876 0.65510062 0.78299492]


In [4]:
!python CIS_few_shot.py --model_name ViT-B/32

loading annotations into memory...
Done (t=1.04s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:04<00:00,  2.15it/s]
loading annotations into memory...
Done (t=0.23s)
creating index...
index created!
100%|█████████████████████████████████████████| 306/306 [00:14<00:00, 21.06it/s]
New best HP, beta: 16.42, alpha: 17.57; accuracy: 70.93
loading annotations into memory...
Done (t=0.54s)
creating index...
index created!
100%|███████████████████████████████████████| 1200/1200 [00:27<00:00, 43.90it/s]

**** Zero-shot CLIP's val accuracy: 54.37. ****

[0.91965855 0.70454545 0.70082645 0.46432818 0.76275304 0.59893048
 0.7926078  0.20055382 0.49275362 0.46026012]
[0.58777279 0.36556604 0.53875476 0.84432432 0.83882458 0.84955752
 0.49243999 0.51843236 0.43243243 0.89215686]
[0.71718062 0.48136646 0.6091954  0.59915612 0.79898219 0.70256142
 0.60746656 0.28922278 0.46062659 0.607245  ]

**** Few-shot CLIP's val accuracy: 70.15. ****

[0.76605125 0.

In [1]:
!python CIS_few_shot.py --model_name ViT-B/16

loading annotations into memory...
Done (t=0.72s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:06<00:00,  1.57it/s]
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
100%|█████████████████████████████████████████| 306/306 [00:16<00:00, 18.89it/s]
New best HP, beta: 19.80, alpha: 25.05; accuracy: 73.09
loading annotations into memory...
Done (t=0.56s)
creating index...
index created!
100%|███████████████████████████████████████| 1200/1200 [01:02<00:00, 19.08it/s]

**** Zero-shot CLIP's val accuracy: 63.01. ****

[0.86378653 0.58518519 0.42571255 0.66764418 0.71805556 0.75147232
 0.76757352 0.26806582 0.24901575 0.57621441]
[0.54541078 0.55896226 0.89199492 0.73837838 0.920748   0.80657396
 0.69188244 0.40229062 0.40222576 0.48179272]
[0.66863382 0.57177322 0.57635468 0.70123203 0.80686695 0.77804878
 0.72776521 0.32174037 0.30759878 0.52479024]

**** Few-shot CLIP's val accuracy: 72.27. ****

[0.86790698 0.

In [2]:
!python CIS_few_shot.py --model_name ViT-L/14

loading annotations into memory...
Done (t=0.76s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:12<00:00,  1.27s/it]
loading annotations into memory...
Done (t=0.21s)
creating index...
index created!
100%|█████████████████████████████████████████| 306/306 [00:54<00:00,  5.60it/s]
New best HP, beta: 12.94, alpha: 10.08; accuracy: 76.42
loading annotations into memory...
Done (t=0.55s)
creating index...
index created!
100%|███████████████████████████████████████| 1200/1200 [03:32<00:00,  5.65it/s]

**** Zero-shot CLIP's val accuracy: 64.98. ****

[0.95718728 0.46082337 0.60152931 0.6213355  0.55019199 0.87692308
 0.79513281 0.19289216 0.58128079 0.71577726]
[0.64216945 0.81839623 0.89961881 0.82486486 0.89314337 0.57648546
 0.70860896 0.28167502 0.75039746 0.86414566]
[0.76865457 0.58963466 0.7209776  0.70877845 0.68092329 0.69565217
 0.74938164 0.22897876 0.65510062 0.78299492]

**** Few-shot CLIP's val accuracy: 74.42. ****

[0.85348315 0.

In [3]:
!python CIS_few_shot_train.py --model_name ViT-B/32

loading annotations into memory...
Done (t=0.71s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:04<00:00,  2.26it/s]
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
100%|█████████████████████████████████████████| 306/306 [00:07<00:00, 41.68it/s]
New best HP, beta: 1.00, alpha: 5.09; accuracy: 67.77
loading annotations into memory...
Done (t=0.72s)
creating index...
index created!
Train Epoch: 0 / 20
100%|███████████████████████████████████████████| 22/22 [00:31<00:00,  1.45s/it]
LR: 0.050000, Acc: 0.7644 (4267.0/5582), Loss: 0.9652
**** Tip-Adapter-F's test accuracy: 72.52. ****

Alpha:Parameter containing:
tensor([[5.02],
        [5.08],
        [4.94],
        [5.04],
        [5.04],
        [5.00],
        [4.92],
        [5.09],
        [4.98],
        [5.02]], device='cuda:0', dtype=torch.float16, requires_grad=True)

Train Epoch: 1 / 20
100%|███████████████████████████████████████████| 22/22 [00:06<

In [4]:
!python CIS_few_shot_train.py --model_name ViT-B/16

loading annotations into memory...
Done (t=1.24s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:06<00:00,  1.60it/s]
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
100%|█████████████████████████████████████████| 306/306 [00:29<00:00, 10.47it/s]
New best HP, beta: 1.00, alpha: 5.09; accuracy: 69.24
loading annotations into memory...
Done (t=0.74s)
creating index...
index created!
Train Epoch: 0 / 20
100%|███████████████████████████████████████████| 22/22 [00:10<00:00,  2.02it/s]
LR: 0.050000, Acc: 0.7696 (4296.0/5582), Loss: 0.7885
**** Tip-Adapter-F's test accuracy: 81.16. ****

Alpha:Parameter containing:
tensor([[4.89],
        [4.97],
        [4.98],
        [5.07],
        [5.01],
        [4.99],
        [5.07],
        [4.94],
        [5.02],
        [5.00]], device='cuda:0', dtype=torch.float16, requires_grad=True)

Train Epoch: 1 / 20
100%|███████████████████████████████████████████| 22/22 [00:11<

In [5]:
!python CIS_few_shot_train.py --model_name ViT-L/14

loading annotations into memory...
Done (t=1.20s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:12<00:00,  1.23s/it]
loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
100%|█████████████████████████████████████████| 306/306 [00:57<00:00,  5.30it/s]
New best HP, beta: 1.00, alpha: 5.09; accuracy: 74.62
loading annotations into memory...
Done (t=0.81s)
creating index...
index created!
Train Epoch: 0 / 20
100%|███████████████████████████████████████████| 22/22 [00:36<00:00,  1.65s/it]
LR: 0.050000, Acc: 0.7562 (4221.0/5582), Loss: 1.4565
**** Tip-Adapter-F's test accuracy: 82.68. ****

Alpha:Parameter containing:
tensor([[5.10],
        [4.98],
        [4.99],
        [4.72],
        [5.02],
        [5.02],
        [4.84],
        [5.06],
        [5.03],
        [5.02]], device='cuda:0', dtype=torch.float16, requires_grad=True)

Train Epoch: 1 / 20
100%|███████████████████████████████████████████| 22/22 [00:33<