In [9]:
!python mocs_zero_shot.py --model_name ViT-B/32

loading annotations into memory...
Done (t=0.33s)
creating index...
index created!
100%|████████████████████████████████████| 18965/18965 [00:53<00:00, 356.79it/s]

**** Zero-shot CLIP's val accuracy: 60.67. FPS:443.71 ****

[0.97144252 0.8049922  0.1398773  0.21463415 0.13653137 0.18421053
 0.88408744 0.13742072 0.1209564  0.18085106 0.31395349 0.08507223
 0.16624285]
[0.68279293 0.5308642  0.3713355  0.24309392 0.43274854 0.47804878
 0.66323417 0.11882998 0.50588235 0.07053942 0.60335196 0.33125
 0.63470874]
[0.80193431 0.63980161 0.20320856 0.22797927 0.20757363 0.26594301
 0.75789932 0.12745098 0.19523269 0.10149254 0.41300191 0.13537676
 0.26347607]


In [10]:
!python mocs_zero_shot.py --model_name ViT-B/16

loading annotations into memory...
Done (t=0.33s)
creating index...
index created!
100%|████████████████████████████████████| 18965/18965 [00:54<00:00, 350.39it/s]

**** Zero-shot CLIP's val accuracy: 61.47. FPS:431.63 ****

[0.98323114 0.82334385 0.14733179 0.25846154 0.00956938 0.08382066
 0.85120968 0.52547771 0.03321523 0.02314815 0.29558011 0.0513834
 0.75816993]
[0.6739578  0.53703704 0.41368078 0.2320442  0.03508772 0.2097561
 0.8051106  0.15082267 0.44117647 0.02074689 0.59776536 0.56875
 0.5631068 ]
[0.79973536 0.65006227 0.21727973 0.24454148 0.01503759 0.11977716
 0.82751862 0.234375   0.06177924 0.02188184 0.39556377 0.09425168
 0.64623955]


In [11]:
!python mocs_zero_shot.py --model_name ViT-L/14

loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
100%|████████████████████████████████████| 18965/18965 [02:00<00:00, 157.51it/s]

**** Zero-shot CLIP's val accuracy: 72.23. FPS:171.57 ****

[0.96639745 0.77777778 0.13297872 0.38132296 0.57142857 0.23789174
 0.92810761 0.25155925 0.04061896 0.1589404  0.19280576 0.0647349
 0.8024948 ]
[0.83136044 0.76337449 0.16286645 0.27071823 0.21052632 0.81463415
 0.76315789 0.22120658 0.12352941 0.09958506 0.74860335 0.65625
 0.4684466 ]
[0.89380735 0.77050883 0.14641288 0.31663974 0.30769231 0.36824697
 0.83758895 0.23540856 0.06113537 0.12244898 0.30663616 0.11784512
 0.59157088]


In [15]:
!python mocs_few_shot.py --model_name ViT-B/32

loading annotations into memory...
Done (t=2.16s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:04<00:00,  2.12it/s]
loading annotations into memory...
Done (t=0.50s)
creating index...
index created!
100%|█████████████████████████████████████████| 593/593 [00:12<00:00, 48.72it/s]
New best HP, beta: 0.10, alpha: 15.07; accuracy: 73.77

**** Zero-shot CLIP's val accuracy: 60.70. ****

[0.97109756 0.80218069 0.14268143 0.21654501 0.13914657 0.1852552
 0.88543788 0.13578947 0.12184874 0.17894737 0.31213873 0.08507223
 0.166295  ]
[0.68305027 0.52983539 0.37785016 0.24585635 0.43859649 0.47804878
 0.66323417 0.1179159  0.51176471 0.07053942 0.60335196 0.33125
 0.63349515]
[0.80199416 0.63816605 0.20714286 0.23027167 0.21126761 0.26702997
 0.75839512 0.12622309 0.19683258 0.10119048 0.41142857 0.13537676
 0.26343679]

**** Few-shot CLIP's val accuracy: 73.80. ****

[0.95197663 0.81991814 0.12822049 0.30100334 0.14184397 0.21035599
 0.94662577 0.

In [16]:
!python mocs_few_shot.py --model_name ViT-B/16

loading annotations into memory...
Done (t=2.01s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:04<00:00,  2.02it/s]
loading annotations into memory...
Done (t=0.50s)
creating index...
index created!
100%|█████████████████████████████████████████| 593/593 [00:18<00:00, 31.51it/s]
New best HP, beta: 0.10, alpha: 15.07; accuracy: 74.23

**** Zero-shot CLIP's val accuracy: 61.43. ****

[0.98322064 0.82464455 0.14767442 0.26006192 0.00961538 0.08576998
 0.85120968 0.52258065 0.03317116 0.02314815 0.29639889 0.05103758
 0.75609756]
[0.67352891 0.53703704 0.41368078 0.2320442  0.03508772 0.21463415
 0.8051106  0.14808044 0.44117647 0.02074689 0.59776536 0.56875
 0.56432039]
[0.79942985 0.65046729 0.2176521  0.24525547 0.01509434 0.12256267
 0.82751862 0.23076923 0.061703   0.02188184 0.3962963  0.09366958
 0.64628214]

**** Few-shot CLIP's val accuracy: 74.26. ****

[0.96497457 0.78606965 0.11038635 0.34562212 0.20430108 0.25896414
 0.87446074 0

In [17]:
!python mocs_few_shot.py --model_name ViT-L/14

loading annotations into memory...
Done (t=2.00s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:11<00:00,  1.16s/it]
loading annotations into memory...
Done (t=0.50s)
creating index...
index created!
100%|█████████████████████████████████████████| 593/593 [01:11<00:00,  8.33it/s]
New best HP, beta: 13.23, alpha: 5.09; accuracy: 81.01

**** Zero-shot CLIP's val accuracy: 72.22. ****

[0.96630446 0.77917981 0.13297872 0.3828125  0.578125   0.23857143
 0.92807425 0.2515528  0.03861004 0.15686275 0.19164265 0.06481481
 0.8024948 ]
[0.83144622 0.76234568 0.16286645 0.27071823 0.21637427 0.81463415
 0.76277651 0.22212066 0.11764706 0.09958506 0.74301676 0.65625
 0.4684466 ]
[0.89381714 0.77067083 0.14641288 0.3171521  0.31489362 0.36906077
 0.83734561 0.23592233 0.05813953 0.12182741 0.30469645 0.11797753
 0.59157088]

**** Few-shot CLIP's val accuracy: 81.02. ****

[0.95196877 0.74035748 0.25609756 0.42929293 0.5        0.17816684
 0.9333996  0

In [4]:
!python mocs_few_shot_train.py --model_name ViT-B/32

loading annotations into memory...
Done (t=2.21s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:07<00:00,  1.32it/s]
loading annotations into memory...
Done (t=0.53s)
creating index...
index created!
  4%|█▍                                        | 21/593 [00:01<00:19, 29.64it/s]

100%|█████████████████████████████████████████| 593/593 [00:13<00:00, 43.46it/s]
New best HP, beta: 1.00, alpha: 2.60; accuracy: 72.80
loading annotations into memory...
Done (t=2.27s)
creating index...
index created!
Train Epoch: 0 / 20
100%|███████████████████████████████████████████| 46/46 [00:49<00:00,  1.07s/it]
LR: 0.050000, Acc: 0.7997 (9349.0/11690), Loss: 1.0689
**** Tip-Adapter-F's test accuracy: 87.56. ****

Alpha:Parameter containing:
tensor([[2.86],
        [2.77],
        [2.79],
        [3.16],
        [2.82],
        [2.67],
        [2.60],
        [2.64],
        [2.71],
        [2.78],
        [3.32],
        [2.65],
        [2.62]], device='cuda:0', dtype=torch.float16, requires_grad=True)

Train Epoch: 1 / 20
100%|███████████████████████████████████████████| 46/46 [00:10<00:00,  4.39it/s]
LR: 0.050000, Acc: 0.8899 (10403.0/11690), Loss: 0.3768
**** Tip-Adapter-F's test accuracy: 88.07. ****

Alpha:Parameter containing:
tensor([[2.72],
        [2.68],
        [2.67],

In [5]:
!python mocs_few_shot_train.py --model_name ViT-B/16

loading annotations into memory...
Done (t=2.15s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:09<00:00,  1.00it/s]
loading annotations into memory...
Done (t=0.51s)
creating index...
index created!
100%|█████████████████████████████████████████| 593/593 [00:21<00:00, 28.18it/s]
New best HP, beta: 1.00, alpha: 2.60; accuracy: 73.02
loading annotations into memory...
Done (t=2.38s)
creating index...
index created!
Train Epoch: 0 / 20
100%|███████████████████████████████████████████| 46/46 [00:22<00:00,  2.06it/s]
LR: 0.050000, Acc: 0.8521 (9961.0/11690), Loss: 0.5559
**** Tip-Adapter-F's test accuracy: 88.51. ****

Alpha:Parameter containing:
tensor([[2.52],
        [2.57],
        [2.49],
        [2.54],
        [2.46],
        [2.44],
        [2.52],
        [2.52],
        [2.47],
        [2.55],
        [2.51],
        [2.51],
        [2.48]], device='cuda:0', dtype=torch.float16, requires_grad=True)

Train Epoch: 1 / 20
100%|█████████

In [6]:
!python mocs_few_shot_train.py --model_name ViT-L/14

loading annotations into memory...
Done (t=2.05s)
creating index...
index created!
 70%|██████████████████████████████▊             | 7/10 [00:14<00:06,  2.06s/it]

100%|███████████████████████████████████████████| 10/10 [00:20<00:00,  2.03s/it]
loading annotations into memory...
Done (t=0.53s)
creating index...
index created!
100%|█████████████████████████████████████████| 593/593 [02:31<00:00,  3.91it/s]
New best HP, beta: 1.00, alpha: 2.60; accuracy: 79.26
loading annotations into memory...
Done (t=2.21s)
creating index...
index created!
Train Epoch: 0 / 20
100%|███████████████████████████████████████████| 46/46 [01:14<00:00,  1.61s/it]
LR: 0.050000, Acc: 0.8689 (10157.0/11690), Loss: 0.4995
**** Tip-Adapter-F's test accuracy: 90.32. ****

Alpha:Parameter containing:
tensor([[2.49],
        [2.56],
        [2.51],
        [2.54],
        [2.59],
        [2.54],
        [2.49],
        [2.49],
        [2.49],
        [2.59],
        [2.50],
        [2.39],
        [2.53]], device='cuda:0', dtype=torch.float16, requires_grad=True)

Train Epoch: 1 / 20
100%|███████████████████████████████████████████| 46/46 [01:29<00:00,  1.95s/it]
LR: 0.050000, A

In [18]:
!python mocs_few_shot_FPS.py --model_name ViT-B/32
!python mocs_few_shot_FPS.py --model_name ViT-B/16
!python mocs_few_shot_FPS.py --model_name ViT-L/14

loading annotations into memory...
Done (t=2.01s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:04<00:00,  2.07it/s]
loading annotations into memory...
Done (t=0.49s)
creating index...
index created!
100%|████████████████████████████████████| 18965/18965 [00:54<00:00, 345.26it/s]

**** Few-shot CLIP's val accuracy: 66.07. FPS:345.10****

loading annotations into memory...
Done (t=2.02s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:04<00:00,  2.01it/s]
loading annotations into memory...
Done (t=0.49s)
creating index...
index created!
100%|████████████████████████████████████| 18965/18965 [00:55<00:00, 342.59it/s]

**** Few-shot CLIP's val accuracy: 65.75. FPS:342.42****

loading annotations into memory...
Done (t=2.01s)
creating index...
index created!
100%|███████████████████████████████████████████| 10/10 [00:11<00:00,  1.16s/it]
loading annotations into memory...
Done (t=0.49s)
creating ind